Repository WildCodeSchool-2023-09/JS-RMT-React_If-Projet3-Externatic, pull requests merged in 2024-01, with the labels that each got.

#7 consultant
  backend/database/schema.sql
  backend/src/app.js
  backend/src/controllers/companyControllers.js
  backend/src/models/CompanyManager.js
  backend/src/router.js
  backend/src/tables.js
  frontend/src/components/card/CompanyCard.css
  frontend/src/components/card/CompanyCard.jsx
  frontend/src/main.jsx
  frontend/src/pages/consultant/ConsultantCompany.css
  frontend/src/pages/consultant/ConsultantCompany.jsx
  frontend/src/pages/layout/ConsultantPage.css
  frontend/src/pages/layout/ConsultantPage.jsx
Labels: invalid

#9 Feat@display all jobs
  backend/database/schema.sql
  backend/src/controllers/jobControllers.js
  backend/src/models/JobManager.js
  backend/src/router.js
  backend/src/tables.js
  frontend/.eslintrc.json
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/components/AllJobs.css
  frontend/src/components/AllJobs.jsx
  frontend/src/components/Collapser.css
  frontend/src/components/Collapser.jsx
  frontend/src/components/Counter.jsx
  frontend/src/components/JobCard.css
  frontend/src/components/JobCard.jsx
  frontend/src/components/Pagination.css
  frontend/src/components/Pagination.jsx
  frontend/src/contexts/context.jsx
  frontend/src/main.jsx
  frontend/src/pages/AllJobsPage.css
  frontend/src/pages/AllJobsPage.jsx
Labels: review formateur

#8 rajout du Footer + rajout sur toute les page + CSS responsive
  frontend/src/App.jsx
  frontend/src/Layout.jsx
  frontend/src/components/Footer.css
  frontend/src/components/Footer.jsx
  frontend/src/main.jsx
  frontend/src/pages/HomePage.jsx
Labels: review formateur

#11 Insert des données dans la DB depuis seed
  backend/database/data/applicationStatus.json
  backend/database/data/company.json
  backend/database/data/job.json
  backend/database/data/role.json
  backend/database/data/user.json
  backend/database/schema.sql
  backend/seed.js
Labels: review formateur

#10 Us nav bar
  backend/database/schema.sql
  frontend/src/App.jsx
  frontend/src/Layout.jsx
  frontend/src/components/JobCard.css
  frontend/src/components/NavBar.css
  frontend/src/components/NavBar.jsx
  frontend/src/public/externatic.png
Labels: review formateur

#13 Affichage de 9 jobs sur le chargement de la page
  backend/src/models/JobManager.js
  backend/src/router.js
  frontend/src/pages/AllJobsPage.jsx
Labels: review formateur

#15 Filter jobs
  backend/src/controllers/jobControllers.js
  backend/src/models/JobManager.js
  backend/src/router.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/FiltersBar.css
  frontend/src/components/FiltersBar.jsx
  frontend/src/components/Pagination.jsx
  frontend/src/components/SelectExternatic.jsx
  frontend/src/main.jsx
  frontend/src/pages/AllJobsPage.jsx
Labels: review team

#17 Us connexion
  backend/database/schema.sql
  backend/package-lock.json
  backend/package.json
  backend/src/app.js
  backend/src/controllers/userControllers.js
  backend/src/middleware/checkCredentials.js
  backend/src/models/UserManager.js
  backend/src/router.js
  backend/src/services/hash.js
  backend/src/services/jwt.js
  backend/src/tables.js
  backend/src/validators/validateUser.js
  frontend/src/components/NavBar.css
  frontend/src/components/NavBar.jsx
  frontend/src/components/reusable/button.css
  frontend/src/components/reusable/formInput.css
  frontend/src/contexts/auth.jsx
  frontend/src/main.jsx
  frontend/src/pages/FormLogin.css
  frontend/src/pages/FormLogin.jsx
  frontend/src/services/connexion.js
Labels: review formateur

#18 Barre de recherche fonctionnelle
  backend/src/controllers/jobControllers.js
  backend/src/models/JobManager.js
  frontend/src/components/Pagination.jsx
  frontend/src/components/SearchBar.css
  frontend/src/components/SearchBar.jsx
  frontend/src/pages/HomePage.jsx
Labels: review formateur

#19 formulaire d'inscription
  backend/src/controllers/userControllers.js
  backend/src/models/UserManager.js
  backend/src/router.js
  backend/src/services/hash.js
  frontend/src/main.jsx
  frontend/src/pages/FormLogin.jsx
  frontend/src/pages/FormRegister.css
  frontend/src/pages/FormRegister.jsx
Labels: review formateur

#20 rajout d'un carrousel page d'accueil
  backend/src/controllers/jobControllers.js
  backend/src/models/JobManager.js
  backend/src/router.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.css
  frontend/src/components/AllJobs.jsx
  frontend/src/components/Carousel.css
  frontend/src/components/CarouselCompanies.css
  frontend/src/components/CarouselCompanies.jsx
  frontend/src/components/CarouselJobs.jsx
  frontend/src/components/JobCard.css
  frontend/src/components/JobCard.jsx
  frontend/src/components/SearchBar.css
  frontend/src/components/SearchBar.jsx
  frontend/src/main.jsx
  frontend/src/pages/HomePage.css
  frontend/src/pages/HomePage.jsx
  frontend/src/public/Group 102.png
  frontend/src/public/Group 103.png
  frontend/src/public/Group 104.png
  frontend/src/public/Group 105.png
  frontend/src/public/Group 90.png
  frontend/src/public/Group 91.png
  frontend/src/public/Group 92.png
  frontend/src/public/Group 93.png
  frontend/src/public/externatic-background.png
  frontend/src/public/sfddsfdfsfddf.png
  frontend/vite.config.js
  package-lock.json
Labels: review formateur

#22 creation page admin et recupération des entreprises via route get
  backend/database/schema.sql
  backend/src/controllers/userControllers.js
  backend/src/middleware/checkCredentials.js
  backend/src/models/UserManager.js
  backend/src/router.js
  frontend/src/components/AdminNavBar.css
  frontend/src/components/AdminNavBar.jsx
  frontend/src/components/NavBar.jsx
  frontend/src/contexts/auth.jsx
  frontend/src/main.jsx
  frontend/src/pages/AdminPage.css
  frontend/src/pages/AdminPage.jsx
  frontend/src/pages/AdminSpecific.css
  frontend/src/pages/AdminSpecific.jsx
  frontend/src/pages/FormLogin.jsx
Labels: review formateur

#27 Modif
  backend/.env.sample
  backend/src/services/jwt.js
Labels: review formateur

#28 Feat onejob
  backend/src/controllers/jobControllers.js
  backend/src/models/JobManager.js
  backend/src/router.js
  frontend/src/components/JobCard.jsx
  frontend/src/main.jsx
  frontend/src/pages/consultant/ConsultantCompany.jsx
  frontend/src/pages/consultant/ConsultantJobOffre.css
  frontend/src/pages/consultant/ConsultantJobOffre.jsx
Labels: review formateur

#31 ajout fonctionnalité ajout d'entreprise
  backend/src/controllers/companyControllers.js
  backend/src/models/CompanyManager.js
  backend/src/router.js
  frontend/src/components/AdminNavBar.jsx
  frontend/src/components/reusable/button.css
  frontend/src/main.jsx
  frontend/src/pages/AdminSpecific.css
  frontend/src/pages/AdminSpecific.jsx
  frontend/src/pages/FormCompany.css
  frontend/src/pages/FormCompany.jsx
Labels: review formateur

#32 ajout fonctionnalité update company
  backend/src/controllers/companyControllers.js
  backend/src/models/CompanyManager.js
  backend/src/router.js
  frontend/src/main.jsx
  frontend/src/pages/AdminSpecific.css
  frontend/src/pages/AdminSpecific.jsx
  frontend/src/pages/FormCompany.jsx
Labels: review formateur

#34 ajout validator sur route add et edit company
  backend/src/router.js
  backend/src/validators/validateCompany.js
  frontend/src/main.jsx
  frontend/src/pages/AdminSpecific.jsx
  frontend/src/pages/FormCompany.jsx
Labels: review formateur

#35 correction ajout d'un job + modif select
  frontend/src/assets/selectStyle.js
  frontend/src/components/SelectConsultant.jsx
  frontend/src/components/SelectExternatic.jsx
  frontend/src/components/SelectFromList.jsx
  frontend/src/pages/AdminJobs.jsx
  frontend/src/pages/Adminjobs.css
Labels: review team

#33 Job
  backend/database/schema.sql
  backend/src/controllers/jobControllers.js
  backend/src/router.js
  frontend/src/assets/Logohead.svg
  frontend/src/components/headJobs.jsx
  frontend/src/components/modal.jsx
  frontend/src/main.jsx
  frontend/src/pages/jobId.jsx
  frontend/src/styles/headJobs.css
  frontend/src/styles/jobId.css
  frontend/src/styles/modal.css
Labels: review formateur
