Repository WildCodeSchool-2023-09/JS-RMT-React_If-Projet3-Externatic, pull requests merged in 2024-02, with the labels that each got.

#39 reparation route vers jobId
  frontend/src/components/JobCard.jsx
Labels: review formateur

#40 rajout du bouton de deconnexion + modification du register
  backend/public/assets/images/2023_Parcours_MIXTE_BenoÃ®t_Dossier_professionnel_1707121891241.pdf
  backend/public/assets/images/EXTERNATIC-LOGO-CHARTE_1707121745686.pdf
  backend/src/controllers/userControllers.js
  backend/src/models/UserManager.js
  backend/src/validators/validateUser.js
  frontend/src/components/NavBar.css
  frontend/src/components/NavBar.jsx
  frontend/src/contexts/auth.jsx
  frontend/src/pages/FormRegister.css
  frontend/src/pages/FormRegister.jsx
Labels: review formateur

#37 Us candidat
  backend/database/data/job.json
  backend/database/schema.sql
  backend/package-lock.json
  backend/package.json
  backend/public/assets/images/favicon.png
  backend/src/app.js
  backend/src/controllers/userControllers.js
  backend/src/models/UserManager.js
  backend/src/router.js
  backend/src/services/upload.js
  backend/src/validators/validateAccount.js
  frontend/src/components/NavBar.jsx
  frontend/src/main.jsx
  frontend/src/pages/AdminPage.jsx
  frontend/src/pages/CandidatAccount.css
  frontend/src/pages/CandidatAccount.jsx
Labels: review formateur

#42 ajout symboles + et - dans collapser, et ajour barre de recherche sur…
  frontend/src/components/Collapser.css
  frontend/src/components/Collapser.jsx
  frontend/src/components/FiltersBar.css
  frontend/src/components/SearchBar.css
  frontend/src/components/SearchBar.jsx
  frontend/src/pages/AllJobsPage.css
  frontend/src/pages/AllJobsPage.jsx
  frontend/src/pages/HomePage.jsx
Labels: review formateur

#38 supression d'un job
  backend/database/schema.sql
  backend/src/controllers/jobControllers.js
  backend/src/middleware/checkCredentialsConsultant.js
  backend/src/models/JobManager.js
  backend/src/router.js
  frontend/src/components/ConsultantJobCard.jsx
  frontend/src/components/JobCard.css
  frontend/src/components/JobCard.jsx
  frontend/src/main.jsx
  frontend/src/pages/AdminJobDelete.jsx
  frontend/src/pages/Administration.jsx
  frontend/src/pages/consultant/ConsultantJob.jsx
Labels: review team

#44 correction ajout admin
  backend/src/middleware/checkCredentialsConsultant.js
  frontend/src/components/JobCard.jsx
Labels: review formateur

#46 Hot fix css
  backend/seed.js
  backend/src/middleware/checkAdmin.js
  backend/src/middleware/checkConsultant.js
  backend/src/middleware/checkCredentialsConsultant.js
  backend/src/router.js
  frontend/src/components/FiltersBar.css
  frontend/src/components/JobCard.css
  frontend/src/components/NavBar.jsx
  frontend/src/components/SearchBar.jsx
  frontend/src/components/card/AdminCard.css
  frontend/src/components/card/AdminCard.jsx
  frontend/src/components/card/AdminUserCard.jsx
  frontend/src/pages/AdminPage.css
  frontend/src/pages/AdminPage.jsx
  frontend/src/pages/AdminSpecific.jsx
  frontend/src/pages/AllJobsPage.css
Labels: review formateur

#43 Fix css all
  backend/public/assets/images/2023_Parcours_MIXTE_BenoÃ®t_Dossier_professionnel_1707121891241.pdf
  backend/public/assets/images/EXTERNATIC-LOGO-CHARTE_1707121745686.pdf
  frontend/src/components/Carousel.css
  frontend/src/components/CarouselCompanies.css
  frontend/src/components/CarouselCompanies.jsx
  frontend/src/components/CarouselJobs.jsx
  frontend/src/pages/AllJobsPage.css
  frontend/src/pages/CandidatAccount.css
  frontend/src/pages/FormLogin.css
  frontend/src/pages/FormLogin.jsx
  frontend/src/pages/FormRegister.css
  frontend/src/pages/FormRegister.jsx
  frontend/src/pages/HomePage.css
  frontend/src/pages/HomePage.jsx
Labels: review formateur

#48 correction condition access dans jobcard
  frontend/src/components/JobCard.jsx
Labels: review formateur

#45 hotfixstylecss
  frontend/src/components/headJobs.css
  frontend/src/components/headJobs.jsx
  frontend/src/components/modal.css
  frontend/src/components/modal.jsx
  frontend/src/pages/jobId.css
  frontend/src/pages/jobId.jsx
Labels: review formateur

#49 Possibilité pour un candidat de voir ses candidatures
  backend/database/data/applicationStatus.json
  backend/database/schema.sql
  backend/seed.js
  backend/src/controllers/applicationControllers.js
  backend/src/models/ApplicationManager.js
  backend/src/router.js
  backend/src/tables.js
  frontend/src/components/JobCard.jsx
  frontend/src/main.jsx
  frontend/src/pages/AdminSpecific.jsx
  frontend/src/pages/CandidatAccount.css
  frontend/src/pages/CandidatAccount.jsx
  frontend/src/pages/CandidatApplications.css
  frontend/src/pages/CandidatApplications.jsx
  frontend/src/pages/jobId.jsx
Labels: review formateur

#51 Candidatures consultant
  backend/src/controllers/applicationControllers.js
  backend/src/controllers/applicationStatusControllers.js
  backend/src/controllers/userControllers.js
  backend/src/models/ApplicationManager.js
  backend/src/models/ApplicationStatusManager.js
  backend/src/router.js
  backend/src/tables.js
  frontend/src/components/AllJobs.jsx
  frontend/src/components/CarouselJobs.jsx
  frontend/src/components/JobCard.jsx
  frontend/src/components/NavBar.jsx
  frontend/src/contexts/auth.jsx
  frontend/src/main.jsx
  frontend/src/pages/ConsultantApplications.css
  frontend/src/pages/ConsultantApplications.jsx
  frontend/src/pages/FormLogin.jsx
  frontend/src/pages/HomePage.css
  frontend/src/pages/consultant/ConsultantJob.jsx
  frontend/src/pages/layout/ConsultantPage.css
  frontend/src/pages/layout/ConsultantPage.jsx
Labels: review formateur

#55 Fix modal
  frontend/src/components/JobCard.jsx
  frontend/src/components/headJobs.jsx
  frontend/src/components/modal.css
  frontend/src/components/modal.jsx
  frontend/src/pages/jobId.css
  frontend/src/pages/jobId.jsx
Labels: review formateur

#54 Feat validate job
  backend/src/controllers/jobControllers.js
  backend/src/models/JobManager.js
  backend/src/router.js
  backend/src/validators/validateJob.js
  frontend/src/components/JobCard.jsx
  frontend/src/components/SelectConsultant.jsx
  frontend/src/components/SelectFromList.jsx
  frontend/src/main.jsx
  frontend/src/pages/AdminJobs.jsx
  frontend/src/pages/AdminPage.css
  frontend/src/pages/Adminjobs.css
  frontend/src/pages/AllJobsPage.jsx
  frontend/src/pages/consultant/ConsultantCompany.css
  frontend/src/pages/consultant/ConsultantJob.css
  frontend/src/pages/consultant/ConsultantJob.jsx
Labels: review formateur

#56 rajout du css telephone + certain petit correctif
  backend/src/validators/validateAccount.js
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Carousel.css
  frontend/src/components/CarouselCompanies.css
  frontend/src/components/CarouselCompanies.jsx
  frontend/src/components/JobCard.jsx
  frontend/src/components/NavBar.css
  frontend/src/components/SearchBar.css
  frontend/src/components/headJobs.jsx
  frontend/src/pages/CandidatAccount.jsx
  frontend/src/pages/HomePage.css
  frontend/src/pages/HomePage.jsx
  frontend/src/pages/jobId.css
  frontend/src/pages/jobId.jsx
Labels: review team

#60 Patch cv
  backend/database/schema.sql
  backend/src/controllers/applicationControllers.js
  backend/src/controllers/userControllers.js
  backend/src/models/ApplicationManager.js
  backend/src/router.js
  backend/src/services/upload.js
  backend/src/validators/validateAccount.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/MenuBurger.css
  frontend/src/components/MenuBurger.jsx
  frontend/src/components/NavBar.css
  frontend/src/components/NavBar.jsx
  frontend/src/pages/AllJobsPage.css
  frontend/src/pages/CandidatAccount.jsx
  frontend/src/pages/ConsultantApplications.css
  frontend/src/pages/ConsultantApplications.jsx
  frontend/src/pages/consultant/ConsultantJob.jsx
  frontend/src/pages/layout/ConsultantPage.css
  frontend/src/pages/layout/ConsultantPage.jsx
  frontend/src/services/connexionCV.js
Labels: review team, review formateur
